
project_id = "akfieehzgpcapuhdujvf"

[global.env]
RESEND_API_KEY = "{{RESEND_API_KEY}}"
SUPABASE_URL = "https://akfieehzgpcapuhdujvf.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "{{SUPABASE_SERVICE_ROLE_KEY}}"
