
# This file controls the configuration for Supabase CLI
# Only the most commonly used config options are in this file
# See this page for all options: https://supabase.com/docs/guides/cli/config

project_id = "akfieehzgpcapuhdujvf"

[api]
# Point to where you locally run Supabase
# This will be ignored when deploying to Supabase Platform
port = 54321

[db]
port = 54322

[studio]
port = 54323

[functions]
# Function configuration is now in functions/config.toml
