
project_id = "akfieehzgpcapuhdujvf"

[api]
# Point to where you locally run Supabase.
# This will be ignored when deploying to Supabase Platform.
port = 54321

[db]
port = 54322

[studio]
port = 54323

[functions]
port = 54324
