
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akfieehzgpcapuhdujvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZmllZWh6Z3BjYXB1aGR1anZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjM2NTMsImV4cCI6MjA1ODM5OTY1M30.gm5K_CQfX11n5RJxdbdhid4i2xD7wFUBMlR-uTFS_z8";

// Helper method to get the base URL
const getUrl = () => SUPABASE_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = Object.assign(
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY), 
  { getUrl }
);
